### ISSUE TITLE
Why process results in reverse when the results are in descending order

### ISSUE THREAD

**Issue by vivekjuneja** [knes1/elktail#17]
Hi,

I reviewed the code of `elktail.go` and have a question for the function `processResults`.

The code chunk below is part of a check that is done to to process the results. 

```
else { //when results are in descending order, we need to process them in reverse
		for i := len(hits) - 1; i >= 0; i-- {
			hit := hits[i]
			entry := t.processHit(hit)
			timeStamp := entry[t.queryDefinition.TimestampField].(string)
			if timeStamp != t.lastTimeStamp {
				t.lastTimeStamp = timeStamp
			}
			t.lastIDs = append(t.lastIDs, DisplayedEntry{ timeStamp: timeStamp, id: hit.Id })
		}
```
Can you help me understand the reason for processing the logs in reverse when the results are in descending order ?

Some background -
I am hoping to extend your work to add custom field to sort the results upon. Currently it uses `@timestamp`, but I am interested to have this as a configurable option. I also need the sort order to be configurable as well. I was stuck with this code chunk while making my changes.  

It would be really great if you can throw more light on the decision in the code. 

Thanks a ton,
Vivek

**Comment by knes1** [comment]
Sure! Currently Elktail currently always displays results on the screen in the ascending order. Motivation was to mimic how regular unix tail command works.

However, when querying elasticsearch, if we want to fetch last N entries then we need to set max results to N and request ordering of the results by timestamp in desending order. Since elktail displays results on the screen in ascending order, it needs to process results (e.g. print them on the screen) returned from elasticsearch in reverse.

There is one scenario though when we need to issue a query to elasticsearch with order set to asceneding. It happens when we're using date filtering and specifying "date after". To fetch first N entries after a specific date, query to elasticsearch needs to have max results set to N and order to ascending. In this case results are displayed in the same order they're received from elasticsearch.

You can see this in action in NewTail() where tail.order is set to true or false depending whether QueryDefinition.AfterDateTime is configured or not.

I hope this makes sense :)

If you plan to implement custom sort orders please consider how it will inter-operate with other options and make sure it works in a meaningful way in following scenarios:

1) Elktail runs in follow (tailing mode) - I guess that custom ordering would disable tailing mode?
2) Date filtering is applied and only date after is set
3) Date filtering is applied and only date before is set

Let me know if you have additional questions!

**Comment by vivekjuneja** [comment]
@knes1 - Thanks for the explanation.

I will consider your suggestion when making these changes.
