### ISSUE TITLE
Doesn't really use queries?

### ISSUE THREAD

**Issue by JoeOrtiz** [knes1/elktail#2]
I've tried many different variants like:

app:account-service

or

"app:account-service"

or

app:"account-service"

It doesn't really go through such field and give just those results.

**Comment by knes1** [comment]
Hi,
ElasticSearch will treat any terms that have punctuation in them (such as account-service) as separate search terms. So app:account-service is interpreted similarly as app:account OR app:service. You were on the right track to attempt enclosing account-service in the quotation marks, unfortunately, it seems that shell consumes the quotes and elktail sees the parameters without quotes.

Could you please try enclosing entire search term app:"account-service" into single quotes like this:
`'app:"account-service"'`

Let me know if this works for you.

**Comment by JoeOrtiz** [comment]
That works! Thanks for your help.

**Comment by knes1** [comment]
I'm glad it works! However, when I think about it more, elasticsearh's default of treating interpunction the same way as white space usually won't make sense in field searches when searching the logs. Many times field will contain things sparated by dashes, underlines or dots and correct way to quote things in the shell to obtain desired results is less than obvious. In the next version I will modify the query builder to treat all `field:value` expressions to function as if you typed `'field:"value"'` so that your original query will work as expected.

**Comment by JoeOrtiz** [comment]
I just ran into another issue.

What about in the format field.

I tried

%response_data.body

But it isn't fetching it, the mapping looks like so:

```
      "response_data": {
        "properties": {
          "body": {
            "type": "string"
          }
        }
```

Kibana does see it as that though:

response_data.body      string

**Comment by knes1** [comment]
Hi, this issue has been reported over the weekend - #3. It's implemented and fixed in the master and should work now if you pull the latest version and build it. If you downloaded elktail via homebrew or binary releases I'll be doing a release later today and you will be able to update that way too.

**Comment by knes1** [comment]
There's new release available now. Please try updating to v0.1.4 and see if your problem is resolved.
